auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Tveiker's Home
url: http://tveiker.github.io/
feed: /atom.xml
author_info: <a href="http://tveiker.github.io/">Tveiker</a>
